using System.Globalization;
using System.Text;

namespace CAP_Core.Export.Netlist;

/// <summary>
/// Serialises a <see cref="NetlistDocument"/> to a gdsfactory YAML netlist
/// (<c>name/instances/placements/connections/ports</c>), the shape consumed by
/// <c>gdsfactory.read.from_yaml</c> and by SAX's netlist loader. Emission is
/// hand-rolled (no YAML dependency) with <see cref="CultureInfo.InvariantCulture"/>
/// so a locale-de runner never writes <c>1,5</c> (issue #687).
/// </summary>
public class GdsFactoryYamlNetlistWriter
{
    private static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

    /// <summary>Serialises the netlist to gdsfactory YAML text.</summary>
    public string Write(NetlistDocument netlist)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# gdsfactory YAML netlist — generated by Lunima");
        sb.AppendLine("# https://gdsfactory.github.io/gdsfactory/ — load with gf.read.from_yaml(...)");
        sb.AppendLine("# Topology only: component models (S-matrices) live in the PDK.");
        sb.AppendLine($"name: {netlist.Name}");
        sb.AppendLine();
        AppendInstances(sb, netlist.Instances);
        AppendPlacements(sb, netlist.Placements);
        AppendConnections(sb, netlist.Connections);
        AppendPorts(sb, netlist.Ports);
        return sb.ToString();
    }

    private static void AppendInstances(StringBuilder sb, IReadOnlyList<NetlistInstance> instances)
    {
        if (instances.Count == 0)
        {
            sb.AppendLine("instances: {}");
            sb.AppendLine();
            return;
        }

        sb.AppendLine("instances:");
        foreach (var instance in instances)
        {
            sb.AppendLine($"  {instance.Name}:");
            sb.AppendLine($"    component: {instance.ComponentRef}");
            if (instance.Settings.Count == 0) continue;
            sb.AppendLine("    settings:");
            foreach (var (key, value) in instance.Settings)
                sb.AppendLine($"      {key}: {FormatScalar(value)}");
        }
        sb.AppendLine();
    }

    private static void AppendPlacements(StringBuilder sb, IReadOnlyList<NetlistPlacement> placements)
    {
        if (placements.Count == 0)
            return;

        sb.AppendLine("placements:");
        foreach (var placement in placements)
        {
            sb.AppendLine($"  {placement.InstanceName}:");
            sb.AppendLine($"    x: {placement.X.ToString("F3", Inv)}");
            sb.AppendLine($"    y: {placement.Y.ToString("F3", Inv)}");
            sb.AppendLine($"    rotation: {placement.RotationDegrees.ToString("F0", Inv)}");
        }
        sb.AppendLine();
    }

    private static void AppendConnections(StringBuilder sb, IReadOnlyList<NetlistConnection> connections)
    {
        if (connections.Count == 0)
        {
            sb.AppendLine("connections: {}");
            sb.AppendLine();
            return;
        }

        sb.AppendLine("connections:");
        foreach (var conn in connections)
        {
            var comment = conn.IsElectrical ? "  # electrical" : string.Empty;
            sb.AppendLine(
                $"  {conn.InstanceA},{conn.PortA}: {conn.InstanceB},{conn.PortB}{comment}");
        }
        sb.AppendLine();
    }

    private static void AppendPorts(StringBuilder sb, IReadOnlyList<NetlistPort> ports)
    {
        if (ports.Count == 0)
        {
            sb.AppendLine("ports: {}");
            return;
        }

        sb.AppendLine("ports:");
        foreach (var port in ports)
            sb.AppendLine($"  {port.Name}: {port.InstanceName},{port.PinName}");
    }

    /// <summary>
    /// Numbers stay bare YAML scalars; anything else is single-quoted (with embedded
    /// quotes doubled per YAML rules) so odd parameter strings can't corrupt the document.
    /// </summary>
    private static string FormatScalar(string value) =>
        double.TryParse(value, NumberStyles.Float, Inv, out _)
            ? value
            : "'" + value.Replace("'", "''") + "'";
}
