using System.Globalization;
using System.Text;

namespace CAP_Core.Export.Netlist;

/// <summary>
/// Serialises a <see cref="NetlistDocument"/> to the gdsfactory YAML netlist shape
/// (<c>name/instances/placements/connections/ports</c>) — a <b>topology / circuit</b>
/// netlist for SAX and gdsfactory netlist tooling. Note the layout caveat (issue #687):
/// <c>connections</c> list logically-joined port pairs (the circuit graph); in a
/// <c>gf.read.from_yaml</c> <i>layout</i> load gdsfactory treats a connection as abutting
/// (coincident) ports, so components joined on the canvas by waveguide/metal routes are
/// NOT reproduced as drawn routes and <c>placements</c> are informational (µm). Emission is
/// hand-rolled (no YAML dependency) with <see cref="CultureInfo.InvariantCulture"/> so a
/// locale-de runner never writes <c>1,5</c>.
/// </summary>
public class GdsFactoryYamlNetlistWriter
{
    private static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

    /// <summary>Serialises the netlist to gdsfactory YAML text.</summary>
    public string Write(NetlistDocument netlist)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# gdsfactory YAML netlist — generated by Lunima (topology / circuit netlist).");
        sb.AppendLine("# instances + connections describe the circuit graph — for SAX and gdsfactory");
        sb.AppendLine("# netlist tooling. Component models (S-matrices) live in the PDK, not here.");
        sb.AppendLine("# Note: 'placements' are informational (µm); 'connections' are logical port");
        sb.AppendLine("# joins — a gf.read.from_yaml LAYOUT load abuts connected ports and does not");
        sb.AppendLine("# redraw the waveguide/metal routes between spaced components.");
        sb.AppendLine($"name: {netlist.Name}");
        sb.AppendLine();
        AppendInstances(sb, netlist.Instances);
        AppendPlacements(sb, netlist.Placements);
        AppendConnections(sb, netlist.Connections);
        AppendPorts(sb, netlist.Ports);
        return sb.ToString();
    }

    private static void AppendInstances(StringBuilder sb, IReadOnlyList<NetlistInstance> instances)
    {
        if (instances.Count == 0)
        {
            sb.AppendLine("instances: {}");
            sb.AppendLine();
            return;
        }

        sb.AppendLine("instances:");
        foreach (var instance in instances)
        {
            sb.AppendLine($"  {instance.Name}:");
            // The component ref can fall back to a user-facing display name (a component with
            // neither gdsFactoryFunction nor nazcaFunction), which may contain spaces / ':' / '#'
            // — quote it so it can't corrupt the YAML (#687 review).
            sb.AppendLine($"    component: {PlainOrQuoted(instance.ComponentRef)}");
            if (instance.Settings.Count == 0) continue;
            sb.AppendLine("    settings:");
            foreach (var (key, value) in instance.Settings)
                sb.AppendLine($"      {key}: {FormatScalar(value)}");
        }
        sb.AppendLine();
    }

    private static void AppendPlacements(StringBuilder sb, IReadOnlyList<NetlistPlacement> placements)
    {
        if (placements.Count == 0)
            return;

        sb.AppendLine("placements:");
        foreach (var placement in placements)
        {
            sb.AppendLine($"  {placement.InstanceName}:");
            sb.AppendLine($"    x: {placement.X.ToString("F3", Inv)}");
            sb.AppendLine($"    y: {placement.Y.ToString("F3", Inv)}");
            sb.AppendLine($"    rotation: {placement.RotationDegrees.ToString("F0", Inv)}");
        }
        sb.AppendLine();
    }

    private static void AppendConnections(StringBuilder sb, IReadOnlyList<NetlistConnection> connections)
    {
        if (connections.Count == 0)
        {
            sb.AppendLine("connections: {}");
            sb.AppendLine();
            return;
        }

        sb.AppendLine("connections:");
        foreach (var conn in connections)
        {
            var comment = conn.IsElectrical ? "  # electrical" : string.Empty;
            sb.AppendLine(
                $"  {conn.InstanceA},{conn.PortA}: {conn.InstanceB},{conn.PortB}{comment}");
        }
        sb.AppendLine();
    }

    private static void AppendPorts(StringBuilder sb, IReadOnlyList<NetlistPort> ports)
    {
        if (ports.Count == 0)
        {
            sb.AppendLine("ports: {}");
            return;
        }

        sb.AppendLine("ports:");
        foreach (var port in ports)
            sb.AppendLine($"  {port.Name}: {port.InstanceName},{port.PinName}");
    }

    /// <summary>
    /// Numbers stay bare YAML scalars; anything else is single-quoted (with embedded
    /// quotes doubled per YAML rules) so odd parameter strings can't corrupt the document.
    /// </summary>
    private static string FormatScalar(string value) =>
        double.TryParse(value, NumberStyles.Float, Inv, out _)
            ? value
            : "'" + value.Replace("'", "''") + "'";

    /// <summary>
    /// Emits a scalar bare when it is a safe YAML plain scalar (letters, digits, and
    /// <c>_ - .</c>), otherwise single-quoted (embedded quotes doubled). Used for the
    /// component reference, which may fall back to a free-form display name.
    /// </summary>
    private static string PlainOrQuoted(string value) =>
        value.Length > 0 && value.All(c => char.IsLetterOrDigit(c) || c is '_' or '-' or '.')
            ? value
            : "'" + value.Replace("'", "''") + "'";
}
